-- ============================================================
-- Universidade BT — Seed inicial (Fase 1)
-- Gerado a partir do conteúdo atual do index.html.
-- Rode DEPOIS de 001_ubt_schema.sql.
-- ============================================================

truncate table ubt_calendar, ubt_faculty, ubt_courses restart identity cascade;

-- ---------- CURSOS ----------
insert into ubt_courses (title,status,format,vagas,carga_horaria,descricao,featured,intl,periodo,inscricoes,link,cronograma,publico,ordem) values (
  'Curso Nacional Nível 1', 'soon', 'Online', 30, 'A definir', 'Formação fundamental para novos treinadores de triathlon. Conteúdo alinhado às diretrizes da World Triathlon e adaptado à realidade brasileira.', true, false, 'A definir', 'A definir', null, null, null, 0);
insert into ubt_courses (title,status,format,vagas,carga_horaria,descricao,featured,intl,periodo,inscricoes,link,cronograma,publico,ordem) values (
  'Curso Nacional Nível 2', 'sold', 'Online', 30, 'A definir', 'Continuidade da formação para treinadores que já concluíram o Nível 1. 1ª turma encerrada com todas as vagas preenchidas.', true, false, 'A definir', 'Encerradas', null, null, null, 1);
insert into ubt_courses (title,status,format,vagas,carga_horaria,descricao,featured,intl,periodo,inscricoes,link,cronograma,publico,ordem) values (
  'World Triathlon Level 1 Online', 'sold', '100% Online', 20, null, 'Certificação internacional da World Triathlon na modalidade 100% online. Reconhecida em mais de 130 países.', true, true, '03/08/2026 a 09/2026', '08/07 a 15/07/2026', 'https://www.ticketsports.com.br/e/CERTIFICA%C3%87%C3%83O%20INTERNACIONAL%20DE%20TREINADORES%20WORLD%20TRIATHLON%20-%20N%C3%8DVEL%201%20(ONLINE)-87367', '{"inscricoes":"De 08/07/2026 (09h) a 15/07/2026 — ou enquanto durarem as vagas","vagas":"20 vagas","horarios":["Encontros síncronos de 60 min: 18h30 às 19h30 (horário de Brasília)","Encontros síncronos de 90 min: 18h30 às 20h00 (horário de Brasília)"],"encontros":[{"sem":"Welcome Meeting","data":"03/08/2026 (seg) · 60 min"},{"sem":"Semana 1","data":"12/08/2026 (qua) · 60 min"},{"sem":"Semana 2","data":"19/08/2026 (qua) · 60 min"},{"sem":"Semana 3","data":"26/08/2026 (qua) · 60 min"},{"sem":"Semana 4","data":"02/09/2026 (qua) · 60 min"},{"sem":"Semana 5","data":"09/09/2026 (qua) · 90 min • 10/09/2026 (qui) · 60 min"},{"sem":"Semana 6","data":"16/09/2026 (qua) · 90 min • 17/09/2026 (qui) · 60 min"},{"sem":"Semana 7","data":"Avaliações e reuniões individuais (20 a 30 min)"},{"sem":"Semana 8","data":"Avaliações e reuniões individuais (20 a 30 min)"},{"sem":"Semana 9","data":"Avaliações e reuniões individuais (20 a 30 min)"}]}'::jsonb, null, 2);
insert into ubt_courses (title,status,format,vagas,carga_horaria,descricao,featured,intl,periodo,inscricoes,link,cronograma,publico,ordem) values (
  'World Triathlon Level 1 Híbrido', 'open', 'Online + Presencial', 20, null, 'Certificação internacional com módulo presencial intensivo. Experiência prática supervisionada por facilitadores credenciados.', false, true, '13/10 a 29/11/2026', '23/09 a 30/09/2026', 'https://www.ticketsports.com.br/e/CERTIFICA%C3%87%C3%83O%20INTERNACIONAL%20DE%20TREINADORES%20WORLD%20TRIATHLON%20-%20N%C3%8DVEL%201%20(H%C3%8DBRIDO)-87467', '{"inscricoes":"De 23/09/2026 (09h) a 30/09/2026 — ou enquanto durarem as vagas","vagas":"20 vagas","horarios":["Encontros síncronos de 45 min: 18h30 às 19h15 (horário de Brasília)","Encontros síncronos de 60 min: 18h30 às 19h30 (horário de Brasília)"],"encontros":[{"sem":"Welcome Meeting","data":"13/10/2026 (seg) · 60 min"},{"sem":"Semana 1","data":"14/10/2026 (qua) · 60 min"},{"sem":"Semana 2","data":"19/10/2026 (seg) · 45 min • 22/10/2026 (qui) · 60 min"},{"sem":"Semana 3","data":"26/10/2026 (seg) · 45 min • 28/10/2026 (qua) · 60 min"},{"sem":"Semana 4","data":"02/11/2026 (seg) · 45 min • 04/11/2026 (qua) · 60 min"},{"sem":"Semana 5","data":"09/11/2026 (seg) · 45 min • 11/11/2026 (qua) · 60 min"}],"presencial":{"titulo":"Etapa Presencial · Rio de Janeiro (local a definir)","datas":["27/11/2026 (sexta-feira)","28/11/2026 (sábado)","29/11/2026 (domingo)"]}}'::jsonb, null, 3);
insert into ubt_courses (title,status,format,vagas,carga_horaria,descricao,featured,intl,periodo,inscricoes,link,cronograma,publico,ordem) values (
  'Introdução ao Triathlon', 'soon', 'Online', null, null, 'Curso introdutório para conhecer a modalidade, sua estrutura, regras, oportunidades profissionais e modelo de desenvolvimento esportivo da CBTri. Indicado para atletas, pais, estudantes, profissionais da saúde, gestores, oficiais técnicos e comunidade do triathlon.', false, false, 'A definir', 'A definir', null, null, ARRAY['Atletas','Pais','Estudantes','Profissionais da saúde','Gestores','Oficiais técnicos','Comunidade do triathlon']::text[], 4);

-- ---------- CALENDÁRIO ----------
insert into ubt_calendar (curso,periodo,inscricoes,vagas,formato,status,ordem) values (
  'CBTri Nível 1 — Turma 1', '27/02/2026 a 07/03/2026', '02/01/2026 a 03/02/2026', '30/30', 'Online', 'done', 0);
insert into ubt_calendar (curso,periodo,inscricoes,vagas,formato,status,ordem) values (
  'Curso Nacional Nível 1', 'A definir', 'A definir', '30', 'Online', 'soon', 1);
insert into ubt_calendar (curso,periodo,inscricoes,vagas,formato,status,ordem) values (
  'Curso Nacional Nível 2 — 1ª Turma', '2026', 'Encerradas', '30/30', 'Online', 'sold', 2);
insert into ubt_calendar (curso,periodo,inscricoes,vagas,formato,status,ordem) values (
  'World Triathlon Level 1 Online', '03/08 a 09/2026', '08/07 a 15/07/2026', '20/20', '100% Online', 'sold', 3);
insert into ubt_calendar (curso,periodo,inscricoes,vagas,formato,status,ordem) values (
  'World Triathlon Level 1 Híbrido', '13/10 a 29/11/2026', '23/09 a 30/09/2026', '20', 'Online + Presencial', 'open', 4);

-- ---------- CORPO DOCENTE ----------
insert into ubt_faculty (name,role,initials,badge,formacao,cert,experiencia,specs,link,photo_url,guest,ordem) values (
  'Dra. Elinai Freitas Schutz', 'Diretora Técnica CBTri', 'ES', 'WORLD TRIATHLON FACILITATOR', ARRAY['Doutora em Ciências do Movimento Humano','Mestre em Ciências do Movimento Humano','Bacharel e Licenciada em Educação Física (UDESC)']::text[], ARRAY['World Triathlon Level 2 Coach','CAMTRI Level 3 Coach','Coach Developer COB']::text[], ARRAY['Diretora Técnica da CBTri','Facilitadora World Triathlon','Mentora de treinadoras do Programa MIRA/COB','Comissão de Mulheres da Americas Triathlon','Mais de 20 anos no treinamento esportivo e formação de treinadores']::text[], ARRAY['Desenvolvimento de atletas','Formação de treinadores','Triathlon de base','Planejamento esportivo','Gestão técnica']::text[], 'http://lattes.cnpq.br/3263303501266158', 'faculty/dra-elinai-freitas-schutz.jpg', false, 0);
insert into ubt_faculty (name,role,initials,badge,formacao,cert,experiencia,specs,link,photo_url,guest,ordem) values (
  'Prof. Rogério Scheibe', 'Facilitador CBTri e World Triathlon', 'RS', 'WORLD TRIATHLON FACILITATOR', ARRAY['Mestre em Fisiologia do Exercício (UFPR)','Doutorando em andamento','Educação Física','Ciências Biológicas']::text[], ARRAY['Facilitador World Triathlon','Facilitador CBTri']::text[], ARRAY['Head Coach — Federação de Triathlon do Kuwait (2020–2022)','Especialista em desenvolvimento de treinadores','Pesquisador em desempenho humano','Autor de estudos sobre análise de performance no triathlon']::text[], ARRAY['Fisiologia aplicada','Treinamento esportivo','Desenvolvimento de atletas','Performance no triathlon','Educação continuada de treinadores']::text[], 'http://lattes.cnpq.br/0939644820659104', 'faculty/prof-rogerio-scheibe.jpg', false, 1);
insert into ubt_faculty (name,role,initials,badge,formacao,cert,experiencia,specs,link,photo_url,guest,ordem) values (
  'Facilitadores Convidados', 'Especialistas Nacionais e Internacionais', '★', 'GUEST EXPERTS', '{}', '{}', ARRAY['Profissionais nacionais e internacionais convidados para módulos específicos, webinars, clínicas e cursos avançados.']::text[], '{}', null, null, true, 2);
